myNum = (null)
myNum2 = (null)
print("Type a number: \n")
print("%d %d")
myNum = input()
myNum2 = input()
print("Your first number is: %d\n" + myNum)
print("Your second number is: %d\n" + myNum2)
print("Your numbers are: %d %d \n" + myNum + myNum2)
